### ISSUE TITLE
Download songs problem

### ISSUE THREAD

**Issue by zdarin** [ltGuillaume/MusicFolderPlayer#33]
Hello, its very good player i love it but i have found some bugs
download one song its download all folder
when donload folder its download music.js file
and on refresh page shows this on safari
![Screenshot 2020-08-02 at 11 55 15](https://user-images.githubusercontent.com/42121280/89119527-c5271d00-d4b7-11ea-8290-81124d3c6010.png)

**Comment by ltGuillaume** [comment]
Are you sure you're using at least commit https://github.com/ltGuillaume/MusicFolderPlayer/commit/c13fc1f92c357fea686e501f64b37ee8153950a1 (`music.php` also changed)?

I have checked and rechecked, but everything seems to be working fine.

Could you turn on `debug` in `music.ini`, look in the browser console (F12) for any issues and report back?

**Comment by zdarin** [comment]
sorry not last used version now using last version
going to check out all
seam refresh working fine no blank page: ok
when downloading folder or song get this file: music.htmmusic.php.html

**Comment by zdarin** [comment]
in debug seam to be all ok

**Comment by ltGuillaume** [comment]
I just committed a small change. Could you try again?

Please be sure to refresh your browser using Ctrl+F5 after updating `music.js`.

**Comment by zdarin** [comment]
yes now working :) good job

**Comment by ltGuillaume** [comment]
Cool!

@nnjim Is everything working for you as well now?

**Comment by nnjim** [comment]
Hi, I have just download a complete fresh copy of MFP and it is a lot better, but I'm afraid I'm still having a few issues;

I'm trying it with 2 different browsers (MS Edge and Opera, and they  both show the same problems.

I could download a few different song MP3s successfully, but the download folder each time just created an empty folder zip file. 

Then suddenly when I chose and played another different song something changed and it downloaded a music.js file instead of the MP3, then clicking on download folder for that same song it also downloaded a music.js file. Then I went back to the songs I successfully downloaded before and click download, they too just create a music.js file! I tried refreshing the browser & deleted the cookies and restarted the server but it still won't download mp3s anymore!

I've run out of time tonight to investigate further but I'll continue tomorrow.

Thanks, Jim

**Comment by ltGuillaume** [comment]
> I could download a few different song MP3s successfully, but the download folder each time just created an empty folder zip file.

Have you enabled the zip module in PHP? If so, was it a valid zip file, just without files in it, or was it an empty file?

> Then suddenly when I chose and played another different song something changed and it downloaded a music.js file instead of the MP3, then clicking on download folder for that same song it also downloaded a music.js file. Then I went back to the songs I successfully downloaded before and click download, they too just create a music.js file! I tried refreshing the browser & deleted the cookies and restarted the server but it still won't download mp3s anymore!

I'm afraid I need more info:

- What was the full path (folder & filename) of the song that first failed to download?
- Did some error occur in the browser console (F12)?
- Can you find an error in the PHP log?
- Are they really `music.js` files, or `music.php`?
- If you open the downloaded `music.js/php` in a text editor, does it say anything?

**Comment by nnjim** [comment]
I've just done a complete reinstall of XAMPP and the latest MFP.

XAMPP phpinfo shows that zip is installed (this PHP version has it embedded in the PHP core so no need to enable it)

I loaded a  'create zip and download'  PHP test page and this works.

MFP; all the features now work :) (Many thanks for this!) - except 'download folder' function - which just creates an empty zip file eg ThisIsTheLife.zip or Wonderland.zip and the zip produced is always 0 bytes. I've enabled PHP error logging and forced a PHP error to show that logging is working, however downloading the empty zip folder, doesn't log any errors.

I haven't been able to break the song download again!

**Comment by ltGuillaume** [comment]
Cool, thank you for all the work you've done. Testing requires time and you've certainly put some in.

I will set up a new XAMPP env. and use a symbolic link to test it for myself. What OS are you on?

**Comment by nnjim** [comment]
I'm using Win10

I won't have so much time to test for a few days, but you've certainly achieved a lot  last week - I appreciate it!

Thanks, Jim

**Comment by nnjim** [comment]
I just tried removing the symbolic link and putting some 'real' folders in the library folder. Unfortunately the 'download folder' function still creates an empty zip file.

**Comment by ltGuillaume** [comment]
I know, I'm working on it.

The zip creation was tailored to Linux environments only and requires the zip binary. I'm currently trying to get it working with the commandline 7-Zip for Windows, but unfortunately I'm getting an empty zip-file (not 0 bytes, it does contain the actual folder structure with the first file to be zipped in it, but that file is 0 bytes), and an error in the Apache log stating
```
System ERROR:
The pipe has been ended.
```
I'm having trouble finding out if I can fix this somehow, or whether I should try to supply a workaround using cygwin or something.

**Comment by ltGuillaume** [comment]
Alright, that seems to be fixed now. You'll need to put `7za.exe` from the [7-Zip Extra](https://7-zip.org/download.html) package in a folder that's in your Windows path (e.g. C:\Windows).

**Comment by nnjim** [comment]
Yes! It all works. Many, Many thanks for sorting it!  👍👍

I need to buy you a Beer! 

Best regards

Jim

**Comment by ltGuillaume** [comment]
Cool, that's great to hear!

If you have some free time, you might want to have a look at the new rewrite I _finally_ did (see https://github.com/ltGuillaume/MusicFolderPlayer/tree/regexp) in order to give people the chance to stick to their own preferrer folder layout.

You can change the `pathexp` variable inside `music.ini` to make it work with some other layout, such as `artist\album (year)\track. title.extension`.

I had a long look (again) at those donation options (PayPal, Flattr, Ko-fi, BountySource Stripe, Liberapay, GitHub's own trial thing), but I'm a bit creeped out by them when it comes to privacy (but I might be overreacting). Maybe I should just bite the bullet and simply make a new PayPal account (but they need my phone number, not cool).
